browser=chromium

headless=false

base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

environment=QA

timeout=30000

slowmo=0

ai.enabled=true

framework.version=1.0.0

MONGO_URI=mongodb://localhost:27017/
MONGO_DATABASE_NAME=ai_test_assistant